apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  namespace: observability-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
        hec-token: "22222222-2222-2222-2222-222222222222"
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - name: backend1
        image: image-registry.openshift-image-registry.svc:5000/observability-poc/backend1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend1
  namespace: observability-poc
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: backend1