apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: local-edge-collector
  namespace: observability-poc
spec:
  # --- ADD THIS LINE ---
  # Forces the operator to use the contrib distribution instead of core.
  # Note: It is best practice to replace 'latest' with a specific version tag 
  # that matches your OpenTelemetry Operator version (e.g., 0.104.0)
  image: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest"
  # ---------------------
  
  config:
    extensions:
      headers_setter:
        headers:
          - action: insert
            key: X-Scope-OrgID
            from_context: app

    receivers:
      otlp:
        protocols:
          grpc:
            include_metadata: true
            endpoint: 0.0.0.0:4317
          http:
            include_metadata: true
            endpoint: 0.0.0.0:4318

    exporters:
      debug:
        verbosity: detailed
      
      prometheusremotewrite:
        endpoint: "http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
        tls:
          insecure: true
      
      otlphttp/loki:
        endpoint: "http://loki.monitoring.svc.cluster.local:3100/otlp"
        tls:
          insecure: true

      otlp/tempo:
        endpoint: "tempo.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
        auth:
          authenticator: headers_setter

    service:
      extensions: [headers_setter]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, otlp/tempo]
        metrics:
          receivers: [otlp]
          exporters: [debug, prometheusremotewrite]
        logs:
          receivers: [otlp]
          exporters: [debug, otlphttp/loki]