{
 "title": "observavility-demo-old",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "traceId", "query": ".*" },
   { "name": "TraceFilter", "label": "Show Only Failed Traces" }
  ]
 },
 "panels": [
  {
   "title": "Reset",
   "type": "text",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"http://prometheus-stack-grafana.monitoring.svc.cluster.local/d/ad9bsp6/new-dashboard?orgId=1&from=now-15m&to=now&timezone=browser&var-Filters=&var-traceId=.%2A&refresh=5s\" class=\"btn btn-secondary\">Reset Dashboard</a>\n"
   }
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "c264666a", "operator": "=", "scope": "span" },
      {
       "id": "status",
       "isCustomValue": false,
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "value": "$TraceFilter",
       "valueType": "keyword"
      },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{} | select(status, resource.service.name)",
     "spss": 100,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "description": "If specific trace selected, shows only logs related to this trace",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_namespace=\"observability-poc\"} | json | trace_id =~ `.*${traceId}.*`"
    }
   ]
  },
  {
   "title": "View Waterfall of Trace",
   "type": "traces",
   "description": "A trace has to be selected from the traces table to show here",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "filters": [
      { "id": "efb97f40", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [],
       "valueType": "string"
      },
      { "id": "duration-type", "value": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "${traceId}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}