apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: polyglot-instrumentation
  namespace: observability-poc
spec:
  exporter:
    endpoint: "http://local-edge-collector-collector.observability-poc.svc.cluster.local:4318"
  env:
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp