# Net-SNMP snmptrapd Configuration
disableAuthorization yes
authCommunity log,execute,net public
authCommunity log,execute,net private

# Default trap handler
traphandle default /usr/local/bin/traphandler.py
